- nodeset:
    name: devstack-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- nodeset:
    name: legacy-ubuntu-focal
    nodes:
      - name: primary
        label: ubuntu-focal

- job:
    name: devstack-gate-hooks
    parent: legacy-dsvm-base
    run: playbooks/devstack-gate-hooks/run.yaml
    post-run: playbooks/devstack-gate-hooks/post.yaml
    timeout: 3900

- job:
    name: legacy-tempest-neutron-full-stable
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-neutron-full/run.yaml
    post-run: playbooks/legacy/tempest-neutron-full/post.yaml
    timeout: 10800
    nodeset: legacy-ubuntu-focal
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest

- project:
    templates:
      - official-openstack-repo-jobs
      - openstack-python35-jobs
    queue: integrated
    check:
      jobs:
        - openstack-tox-bashate:
            nodeset: ubuntu-bionic
        - openstack-tox-py27
        - devstack-gate-hooks
    gate:
      jobs:
        - openstack-tox-py27
        - devstack-gate-hooks
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-dvr-multinode-full
